// dates.js
// Formato: dateISO (YYYY-MM-DD), city, country, venue, ticketUrl, saleStartUTC (opcional)
window.TOUR_DATES = [
  { dateISO: "2026-08-28", city: "Buenos Aires", country: "Argentina", venue: "Movistar Arena", ticketUrl: "", soldOut: true },
  { dateISO: "2026-08-31", city: "Santiago", country: "Chile", venue: "Movistar Arena", ticketUrl: "", soldOut: true },
  { dateISO: "2026-09-01", city: "Santiago", country: "Chile", venue: "Movistar Arena", ticketUrl: "", soldOut: true },
  { dateISO: "2026-09-05", city: "Medellín", country: "Colombia", venue: "Estadio Atanasio Girardot", ticketUrl: "", soldOut: true },
  { dateISO: "2026-09-04", city: "Medellín", country: "Colombia", venue: "Estadio Atanasio Girardot", ticketUrl: "https://www.ticketmaster.co/event/arcangel-20-aniversario"},
  { dateISO: "2026-09-11", city: "La Paz", country: "Bolivia", venue: "Teatro al Aire Libre", ticketUrl: "https://todotix.com.bo/ticket/arcangel" },
  { dateISO: "2026-09-12", city: "Lima", country: "Perú", venue: "Estadio San Marcos", ticketUrl: "https://www.ticketmaster.pe/event/arcangel-la-8va-maravilla-world-tour-home" },
  { dateISO: "2026-09-17", city: "Tegucigalpa", country: "Honduras", venue: "Estadio Chochi Sosa", ticketUrl: "https://arcangelhn.funcapital.com/checkout/AZ13zZIeqc6gArgEttr" },
  { dateISO: "2026-09-19", city: "Cdad. de Guatemala", country: "Guatemala", venue: "Explanada 5", ticketUrl: "https://ticketasa.gt/events/arcángel/" },
  { dateISO: "2026-09-24", city: "Cdad. de Panamá", country: "Panamá", venue: "CC Amador", ticketUrl: "https://www.eticket.pa/" },
  { dateISO: "2026-09-26", city: "Alajuela", country: "Costa Rica", venue: "Parque Viva", ticketUrl: "https://www.eticket.cr/eventos.aspx?idartista=1136" },
  { dateISO: "2026-08-29", city: "Buenos Aires", country: "Argentina", venue: "Movistar Arena", ticketUrl: "", soldOut: true},
  { dateISO: "2026-08-30", city: "Buenos Aires", country: "Argentina", venue: "Movistar Arena", ticketUrl: "", soldOut: true},
  { dateISO: "2026-09-02", city: "Santiago", country: "Chile", venue: "Movistar Arena", ticketUrl: "https://www.puntoticket.com/arcangel"},
  { dateISO: "2026-10-09", city: "Orlando, FL", country: "USA", venue: "Kia Center", ticketUrl: "https://www.ticketmaster.com/event/220064AEADB86CCE"},
  { dateISO: "2026-10-11", city: "Miami, FL", country: "USA", venue: "Kaseya Center", ticketUrl: "https://www.ticketmaster.com/event/0D0064AC03232957"},
  { dateISO: "2026-10-15", city: "Atlanta, GA", country: "USA", venue: "Coca-Cola Roxy", ticketUrl: "https://www.ticketmaster.com/event/0E0064B4AB4BCB0D"},
  { dateISO: "2026-10-16", city: "Charlotte, NC", country: "USA", venue: "Ovens Auditorium", ticketUrl: "https://www.ticketmaster.com/event/2D0064ACE4844C27"},
  { dateISO: "2026-10-21", city: "Fairfax, VA", country: "USA", venue: "EagleBank Arena", ticketUrl: "https://www.ticketmaster.com/event/150064ADB9B79BE3"},
  { dateISO: "2026-10-22", city: "Wallingford, CT", country: "USA", venue: "Toyota Oakdale Theatre", ticketUrl: "https://www.ticketmaster.com/event/1D0064A5C49686F4"},
  { dateISO: "2026-10-23", city: "Brooklyn, NY", country: "USA", venue: "Barclays Center", ticketUrl: "https://www.ticketmaster.com/event/300064ADA23D61BB"},
  { dateISO: "2026-10-24", city: "Philadelphia, PA", country: "USA", venue: "The Met", ticketUrl: "https://www.ticketmaster.com/event/020064ACD3DEEC4B"},
  { dateISO: "2026-10-28", city: "Boston, MA", country: "USA", venue: "MGM Music Hall at Fenway", ticketUrl: "https://www.ticketmaster.com/event/010064ADC0FD59D3"},
  { dateISO: "2026-10-31", city: "Chicago, IL", country: "USA", venue: "Rosemont Theatre", ticketUrl: "https://www.ticketmaster.com/event/040064AD908D649F"},
  { dateISO: "2026-11-05", city: "Houston, TX", country: "USA", venue: "713 Music Hall", ticketUrl: "https://www.ticketmaster.com/event/3A0064B49C099594"},
  { dateISO: "2026-11-06", city: "Irving, TX", country: "USA", venue: "The Pavilion at Toyota Music Factory", ticketUrl: "https://www.ticketmaster.com/event/0C0064B4F97758BF"},
  { dateISO: "2026-11-15", city: "Denver, CO", country: "USA", venue: "Paramount Theatre", ticketUrl: "https://www.ticketmaster.com/event/1E0064AEB279A359"},
  { dateISO: "2026-11-18", city: "Salt Lake City, UT", country: "USA", venue: "The Union Event Center", ticketUrl: "https://www.ticketmaster.com/event/1E0064B4954A8177"},
  { dateISO: "2026-11-20", city: "Inglewood, CA", country: "USA", venue: "YouTube Theater", ticketUrl: "https://www.ticketmaster.com/event/0A0064A792CA7806"},
  { dateISO: "2026-11-21", city: "San Jose, CA", country: "USA", venue: "San Jose Civic", ticketUrl: "https://www.ticketmaster.com/event/1C0064ACCB0A6B9B"},
  { dateISO: "2026-09-10", city: "Santa Cruz", country: "Bolivia", venue: "Sonilum Plaza", ticketUrl: "https://todotix.com.bo/ticket/arcangelsantacruz"}
];
